#!/bin/bash
set -o nounset -o errexit -o pipefail

#install Jupyter
pip install jsonschema jupyter



# #   # CONFIGURE Jupyter
mkdir -p /home/ubuntu/.jupyter
# mkdir -p /home/ubuntu/.ipython/profile_default 
echo 'c = get_config()' > /home/ubuntu/.ipython/profile_default/ipython_config.py 
echo 'c = get_config()' > /home/ubuntu/.jupyter/jupyter_notebook_config.py

echo '# The default cell execution timeout in nbconvert is 30 seconds, set it to a year' >> /home/ubuntu/.jupyter/jupyter_notebook_config.py
echo 'c.ExecutePreprocessor.timeout = 365*24*60*60' >> /home/ubuntu/.jupyter/jupyter_notebook_config.py
echo 'c = get_config()' > /home/ubuntu/.jupyter/jupyter_notebook_config.py
echo '# Allow embedding of notebooks in iframes' >> /home/ubuntu/.jupyter/jupyter_notebook_config.py
echo 'c.NotebookApp.tornado_settings = { "headers": { "Content-Security-Policy": "frame-ancestors *" } }' >> /home/ubuntu/.jupyter/jupyter_notebook_config.py 
echo "c.NotebookApp.token = ''" >> /home/ubuntu/.jupyter/jupyter_notebook_config.py
#Custom js for domino header
mkdir -p /home/ubuntu/.jupyter/custom/
echo "require(['base/js/namespace'], function(IPython) { IPython._target='_self'; });" >> /home/ubuntu/.jupyter/custom/custom.js 

# Disable the login for Jupyter
 mkdir -p /home/ubuntu/.jupyter 
 printf "\nc.NotebookApp.token = u'' \n\n" >> /home/ubuntu/.jupyter/jupyter_notebook_config.py 
 
 #disable quit button in Jupyter 5.5+
 echo c.NotebookApp.quit_button = False >> /home/ubuntu/.jupyter/jupyter_notebook_config.py
 
 chown -R ubuntu:ubuntu /home/ubuntu/.jupyter 
