#!/bin/bash
#!/bin/bash
set -o nounset -o errexit -o pipefail

IP_ADDR=$(/sbin/ifconfig eth0 | grep "inet addr" | cut -d ":" -f2 | cut -d " " -f1)
CONF_DIR="$HOME/.ipython/profile_default"
CONF_FILE="${CONF_DIR}/ipython_notebook_config.py"

mkdir -p "${CONF_DIR}"


# Replace * in "--ip=*" with the actual IP address of the container
COMMAND='jupyter notebook --no-browser --ip=* 2>&1'
FINAL_COMMAND=$(echo "${COMMAND}" | sed "s/--ip=\\*/--ip=${IP_ADDR}/")

eval ${FINAL_COMMAND}


