#!/bin/bash
set -o nounset -o errexit -o pipefail

IP_ADDR=$(/sbin/ifconfig eth0 | grep "inet addr" | cut -d ":" -f2 | cut -d " " -f1)
CONF_DIR="$HOME/.jupyter"
CONF_FILE="${CONF_DIR}/jupyter_notebook_config.py"

mkdir -p "${CONF_DIR}"

cat <<EOF >>"${CONF_FILE}"
c.NotebookApp.notebook_dir = '${DOMINO_WORKING_DIR}'
c.NotebookApp.tornado_settings = {'headers': {'Content-Security-Policy': 'frame-ancestors *'}}
c.NotebookApp.default_url = '${DOMINO_WORKING_DIR}'
EOF

# Replace * in "--ip=*" with the actual IP address of the container
COMMAND='jupyter notebook --no-browser --ip=* 2>&1'
FINAL_COMMAND=$(echo "${COMMAND}" | sed "s/--ip=\\*/--ip=${IP_ADDR}/")

eval ${FINAL_COMMAND}

